### ISSUE TITLE
text?

### ISSUE THREAD

**Issue by bjarthur** [JuliaImages/ImageDraw.jl#4]
i'm looking for a simple way to draw some text onto an existing array.  is there an easy way to do this?  cairo, luxor, compose, etc. all seem to output to files.  i just want to modify the array i already have.  thanks.

**Comment by mronian** [comment]
This feature does not exist in ImageDraw yet.

I am not familiar with Cairo, does this [link](https://www.cairographics.org/cookbook/pythoncairopil/)(its a python example) help to convert a surface to the Image type?

**Comment by timholy** [comment]
I would wager that Cairo is the way to go here. Convert to a surface, then write on it, and then extract the data again. I'm certain Cairo.jl could use some improvement/cleanup to make that easier. Cairo.jl was mostly written before we had the color types `RGB24`, `ARGB32`, `Gray24`, and `AGray32`, which could be leveraged to provide a much more Julian interface than "naked" `UInt32` arrays. They've crept in a bit (I added some wrappers), but overall it's not exactly pretty.

I wonder if we want to make such capabilities part of ImageDraw, or whether there should be a separate ImageText package. If it were not for the issue of additional binary dependencies, I'd argue for putting it all in ImageDraw; but with the dependency problem, one could get into a situation where one couldn't use any of the features of the package simply because it couldn't be loaded. I don't know how problematic `libcairo` has been; I don't remember seeing a lot of bug reports about it.

**Comment by Evizero** [comment]
> I wonder if we want to make such capabilities part of ImageDraw, or whether there should be a separate ImageText package

For my very egoistic reasons I would vote for keeping the dependencies of ImageDraw to a minimum. Egoistic because I would like a future version of UnicodePlots to use ImageDraw and ImageInTerminal to provide a lot of its functionality, and naturally I aim to keep UnicodePlots as compact as I can

**Comment by bjarthur** [comment]
an alternative to Cairo is FreeType.  @SimonDanisch has done most of what i need in the [FreeTypeAbstraction](https://github.com/JuliaGL/GLVisualize.jl/blob/26694d4265626c0411a3e27dec7d616fe4b4e039/src/FreeTypeAbstraction.jl) module of GLVisualize.  would it make sense to split that out into a separate package called ImageText?

**Comment by SimonDanisch** [comment]
I'm actively working on some Julia/CPU only version of GLVisualize right now... This will bring most of this, I guess ;)
But will obviously take some time!

**Comment by bjarthur** [comment]
@SimonDanisch can you please elaborate?  all i need is to put text onto an image array.  your FreeTypeAbstraction module is very close to doing that.  but i don't need the rest of GLVisualize.  are you saying you've already split it out into it's own package?  if so, could you please share?  if not, would you mind if i went ahead and did that?  thanks.

**Comment by SimonDanisch** [comment]
It actually was at some point: https://github.com/SimonDanisch/FreeTypeAbstraction.jl.
I might want to transfer that repo to JuliaGraphics first, though.
Feel free to update it with the current version in GLVisualize!

Well, you might still want a nice API, caching, fast resolution independent rendering, etc, which is what GLVisualize should offer at some point.
If you need it now and don't mind duplicating some work (for a simple version it should be very little duplication), go ahead and don't wait for GLVisualize! ;)

**Comment by bjarthur** [comment]
i have a [PR](https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/6) which enables one to render text into a matrix.  so i'll close this issue, but would appreciate if everyone could provide feedback over there.
